Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = cutout.availabilitymatrix(shape, excluder)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[59], line 1[0m
[0;32m----> 1[0m A [38;5;241m=[39m [43mcutout[49m[38;5;241;43m.[39;49m[43mavailabilitymatrix[49m[43m([49m[43mshape[49m[43m,[49m[43m [49m[43mexcluder[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/atlite/gis.py:761[0m, in [0;36mcompute_availabilitymatrix[0;34m(cutout, shapes, excluder, nprocesses, disable_progressbar)[0m
[1;32m    759[0m availability [38;5;241m=[39m np[38;5;241m.[39mstack(availability)[:, ::[38;5;241m-[39m[38;5;241m1[39m]  [38;5;66;03m# flip axis, see Notes[39;00m
[1;32m    760[0m coords [38;5;241m=[39m [(shapes[38;5;241m.[39mindex), ([38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m, cutout[38;5;241m.[39mdata[38;5;241m.[39my[38;5;241m.[39mdata), ([38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m, cutout[38;5;241m.[39mdata[38;5;241m.[39mx[38;5;241m.[39mdata)]
[0;32m--> 761[0m [38;5;28;01mreturn[39;00m [43mxr[49m[38;5;241;43m.[39;49m[43mDataArray[49m[43m([49m[43mavailability[49m[43m,[49m[43m [49m[43mcoords[49m[38;5;241;43m=[39;49m[43mcoords[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/xarray/core/dataarray.py:479[0m, in [0;36mDataArray.__init__[0;34m(self, data, coords, dims, name, attrs, indexes, fastpath)[0m
[1;32m    477[0m data [38;5;241m=[39m _check_data_shape(data, coords, dims)
[1;32m    478[0m data [38;5;241m=[39m as_compatible_data(data)
[0;32m--> 479[0m coords, dims [38;5;241m=[39m [43m_infer_coords_and_dims[49m[43m([49m[43mdata[49m[38;5;241;43m.[39;49m[43mshape[49m[43m,[49m[43m [49m[43mcoords[49m[43m,[49m[43m [49m[43mdims[49m[43m)[49m
[1;32m    480[0m variable [38;5;241m=[39m Variable(dims, data, attrs, fastpath[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    482[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(coords, Coordinates):

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/xarray/core/dataarray.py:163[0m, in [0;36m_infer_coords_and_dims[0;34m(shape, coords, dims)[0m
[1;32m    156[0m [38;5;250m[39m[38;5;124;03m"""All the logic for creating a new DataArray"""[39;00m
[1;32m    158[0m [38;5;28;01mif[39;00m (
[1;32m    159[0m     coords [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    160[0m     [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m utils[38;5;241m.[39mis_dict_like(coords)
[1;32m    161[0m     [38;5;129;01mand[39;00m [38;5;28mlen[39m(coords) [38;5;241m!=[39m [38;5;28mlen[39m(shape)
[1;32m    162[0m ):
[0;32m--> 163[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    164[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mcoords is not dict-like, but it has [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(coords)[38;5;132;01m}[39;00m[38;5;124m items, [39m[38;5;124m"[39m
[1;32m    165[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mwhich does not match the [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(shape)[38;5;132;01m}[39;00m[38;5;124m dimensions of the [39m[38;5;124m"[39m
[1;32m    166[0m         [38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m
[1;32m    167[0m     )
[1;32m    169[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(dims, [38;5;28mstr[39m):
[1;32m    170[0m     dims [38;5;241m=[39m (dims,)

[0;31mValueError[0m: coords is not dict-like, but it has 3 items, which does not match the 4 dimensions of the data

